#This is the Mitsuba version of 'Dragon' by Delatronic, downloaded from https://benedikt-bitterli.me/resources/
#The original file may be obtained here: http://www.blendswap.com/blends/view/80766
media = []

[camera]
tonemap = "filmic"
resolution = [
  1.0,
  1.0
]
reconstruction_filter = "tent"
type = "pinhole"
fov = 35.0

  [camera.transform]
  position = [
    58.20600128173828,
    24.92840003967285,
    52.950096130371094
  ]
  look_at = [
    -1.505810022354126,
    5.869430065155029,
    -2.1437699794769287
  ]
  up = [
    0.0,
    1.0,
    0.0
  ]

[integrator]
min_bounces = 0.0
max_bounces = 1.0
enable_consistency_checks = false
enable_two_sided_shading = true
type = "path_tracer"
enable_light_sampling = true
enable_volume_light_sampling = true

[renderer]
overwrite_output_files = true
adaptive_sampling = true
enable_resume_render = false
stratified_sampler = true
scene_bvh = true
spp = 1.0
spp_step = 16.0
checkpoint_interval = "0"
timeout = "0"
output_file = "dragon.png"
hdr_output_file = "dragon.pfm"

[[bsdfs]]
name = "GroundInner"
albedo = 0.456263
type = "lambert"

[[bsdfs]]
name = "GroundOuter"
albedo = 0.456263
type = "lambert"

[[bsdfs]]
name = "Cloth"
albedo = 0.456263
type = "lambert"

[[bsdfs]]
name = "Dragon"
albedo = 0.79311
type = "lambert"

[[bsdfs]]
name = "Blade"
albedo = 0.79311
type = "lambert"

[[bsdfs]]
name = "Sword"
albedo = 0.79311
type = "lambert"

[[bsdfs]]
name = "Deco"
albedo = 0.79311
type = "lambert"

[[bsdfs]]
name = "Diamond"
albedo = 0.79311
type = "lambert"

[[bsdfs]]
name = "Deco2"
albedo = 0.79311
type = "lambert"

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh011.obj"
bsdf = "GroundOuter"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh010.obj"
bsdf = "Cloth"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh005.obj"
bsdf = "GroundOuter"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh006.obj"
bsdf = "GroundOuter"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh012.obj"
bsdf = "GroundInner"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh007.obj"
bsdf = "GroundOuter"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh008.obj"
bsdf = "Dragon"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh013.obj"
bsdf = "Dragon"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh014.obj"
bsdf = "Dragon"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh015.obj"
bsdf = "Dragon"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh004.obj"
bsdf = "Blade"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh009.obj"
bsdf = "Sword"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh003.obj"
bsdf = "Deco"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh002.obj"
bsdf = "Diamond"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh001.obj"
bsdf = "Deco2"

  [primitives.transform]

[[primitives]]
type = "mesh"
smooth = true
backface_culling = false
recompute_normals = false
file = "models/Mesh000.obj"
bsdf = "Deco2"

  [primitives.transform]

[[primitives]]
power = 8.0
type = "infinite_sphere_cap"
sample = true
cap_angle = 10.0

  [primitives.transform]
  scale = [
    1.0,
    1.0,
    0.9999999403953552
  ]
  rotation = [
    46.18659210205078,
    15.152700424194336,
    0.0
  ]