#Conversion of Utah Teapot scene Tungsten Renderer config file
media = []

[camera]
tonemap = "filmic"
resolution = [
  512.0,
  512.0
]
reconstruction_filter = "tent"
type = "pinhole"
fov = 35.0

  [camera.transform]
  position = [
    23.895,
    11.2207,
    0.0400773
  ]
  look_at = [
    -0.953633,
    2.17253,
    -0.0972613
  ]
  up = [
    0.0,
    1.0,
    0.0
  ]

[integrator]
min_bounces = 0.0
max_bounces = 1.0
enable_consistency_checks = false
enable_two_sided_shading = true
type = "path_tracer"
enable_light_sampling = true
enable_volume_light_sampling = true

[renderer]
output_file = "teapot.png"
overwrite_output_files = true
spp = 1.0
hdr_output_file = "teapot.pfm"

[[bsdfs]]
name = "Material"
albedo = 0.9
type = "lambert"
ior = 1.5
thickness = 1.0
sigma_a = 0.0

[[bsdfs]]
name = "Floor"
type = "lambert"

  [bsdfs.albedo]
  type = "checker"
  on_color = [
    0.725,
    0.71,
    0.68
  ]
  off_color = [
    0.325,
    0.31,
    0.25
  ]
  res_u = 20.0
  res_v = 20.0

[[primitives]]
type = "quad"
bsdf = "Floor"

  [primitives.transform]
  scale = [
    113.071,
    113.071,
    113.071
  ]
  rotation = [
    0.0,
    45.0,
    -180.0
  ]

[[primitives]]
emission = "textures/envmap.hdr"
type = "infinite_sphere"
sample = true

  [primitives.transform]
  position = [
    0.0,
    0.0,
    1.17369
  ]
  rotation = [
    0.0,
    -67.2614,
    0.0
  ]

[[primitives]]
type = "mesh"
file = "models/Mesh001.obj"
smooth = true
backface_culling = false
recompute_normals = false
bsdf = "Material"

  [primitives.transform]

[[primitives]]
type = "mesh"
file = "models/Mesh000.obj"
smooth = true
backface_culling = false
recompute_normals = false
bsdf = "Material"

  [primitives.transform]